name = 'email-summarizer-cfworker'
main = "src/index.js"
compatibility_date = "2022-12-05"

# Avoids variables being deleted on deployment
keep_vars = true

[ai]
binding = "AI"

# This variable needs adding within CF Worker Settings
# [vars]
# WEBHOOK_URL = "https://ntfy.sh/your_custom_webhook_url"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
